run:
  concurrency: 4
  timeout: 1m
  issues-exit-code: 1
  tests: true
linters:
  enable:
    - golint
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
