// Code generated by mockery v2.30.1. DO NOT EDIT.

package repository

import (
	models "Nix_trainee_practic/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockPostRepo is an autogenerated mock type for the PostRepo type
type MockPostRepo struct {
	mock.Mock
}

type MockPostRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostRepo) EXPECT() *MockPostRepo_Expecter {
	return &MockPostRepo_Expecter{mock: &_m.Mock}
}

// DeletePost provides a mock function with given fields: id
func (_m *MockPostRepo) DeletePost(id int64) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPostRepo_DeletePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePost'
type MockPostRepo_DeletePost_Call struct {
	*mock.Call
}

// DeletePost is a helper method to define mock.On call
//   - id int64
func (_e *MockPostRepo_Expecter) DeletePost(id interface{}) *MockPostRepo_DeletePost_Call {
	return &MockPostRepo_DeletePost_Call{Call: _e.mock.On("DeletePost", id)}
}

func (_c *MockPostRepo_DeletePost_Call) Run(run func(id int64)) *MockPostRepo_DeletePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockPostRepo_DeletePost_Call) Return(_a0 error) *MockPostRepo_DeletePost_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPostRepo_DeletePost_Call) RunAndReturn(run func(int64) error) *MockPostRepo_DeletePost_Call {
	_c.Call.Return(run)
	return _c
}

// GetPost provides a mock function with given fields: id
func (_m *MockPostRepo) GetPost(id int64) (models.Post, error) {
	ret := _m.Called(id)

	var r0 models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (models.Post, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) models.Post); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Post)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostRepo_GetPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPost'
type MockPostRepo_GetPost_Call struct {
	*mock.Call
}

// GetPost is a helper method to define mock.On call
//   - id int64
func (_e *MockPostRepo_Expecter) GetPost(id interface{}) *MockPostRepo_GetPost_Call {
	return &MockPostRepo_GetPost_Call{Call: _e.mock.On("GetPost", id)}
}

func (_c *MockPostRepo_GetPost_Call) Run(run func(id int64)) *MockPostRepo_GetPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockPostRepo_GetPost_Call) Return(_a0 models.Post, _a1 error) *MockPostRepo_GetPost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostRepo_GetPost_Call) RunAndReturn(run func(int64) (models.Post, error)) *MockPostRepo_GetPost_Call {
	_c.Call.Return(run)
	return _c
}

// GetPostsByUser provides a mock function with given fields: userID
func (_m *MockPostRepo) GetPostsByUser(userID int64) ([]models.Post, error) {
	ret := _m.Called(userID)

	var r0 []models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) ([]models.Post, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(int64) []models.Post); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Post)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostRepo_GetPostsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostsByUser'
type MockPostRepo_GetPostsByUser_Call struct {
	*mock.Call
}

// GetPostsByUser is a helper method to define mock.On call
//   - userID int64
func (_e *MockPostRepo_Expecter) GetPostsByUser(userID interface{}) *MockPostRepo_GetPostsByUser_Call {
	return &MockPostRepo_GetPostsByUser_Call{Call: _e.mock.On("GetPostsByUser", userID)}
}

func (_c *MockPostRepo_GetPostsByUser_Call) Run(run func(userID int64)) *MockPostRepo_GetPostsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockPostRepo_GetPostsByUser_Call) Return(_a0 []models.Post, _a1 error) *MockPostRepo_GetPostsByUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostRepo_GetPostsByUser_Call) RunAndReturn(run func(int64) ([]models.Post, error)) *MockPostRepo_GetPostsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// SavePost provides a mock function with given fields: post
func (_m *MockPostRepo) SavePost(post models.Post) (models.Post, error) {
	ret := _m.Called(post)

	var r0 models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Post) (models.Post, error)); ok {
		return rf(post)
	}
	if rf, ok := ret.Get(0).(func(models.Post) models.Post); ok {
		r0 = rf(post)
	} else {
		r0 = ret.Get(0).(models.Post)
	}

	if rf, ok := ret.Get(1).(func(models.Post) error); ok {
		r1 = rf(post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostRepo_SavePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SavePost'
type MockPostRepo_SavePost_Call struct {
	*mock.Call
}

// SavePost is a helper method to define mock.On call
//   - post models.Post
func (_e *MockPostRepo_Expecter) SavePost(post interface{}) *MockPostRepo_SavePost_Call {
	return &MockPostRepo_SavePost_Call{Call: _e.mock.On("SavePost", post)}
}

func (_c *MockPostRepo_SavePost_Call) Run(run func(post models.Post)) *MockPostRepo_SavePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.Post))
	})
	return _c
}

func (_c *MockPostRepo_SavePost_Call) Return(_a0 models.Post, _a1 error) *MockPostRepo_SavePost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostRepo_SavePost_Call) RunAndReturn(run func(models.Post) (models.Post, error)) *MockPostRepo_SavePost_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePost provides a mock function with given fields: post
func (_m *MockPostRepo) UpdatePost(post models.Post) (models.Post, error) {
	ret := _m.Called(post)

	var r0 models.Post
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Post) (models.Post, error)); ok {
		return rf(post)
	}
	if rf, ok := ret.Get(0).(func(models.Post) models.Post); ok {
		r0 = rf(post)
	} else {
		r0 = ret.Get(0).(models.Post)
	}

	if rf, ok := ret.Get(1).(func(models.Post) error); ok {
		r1 = rf(post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPostRepo_UpdatePost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePost'
type MockPostRepo_UpdatePost_Call struct {
	*mock.Call
}

// UpdatePost is a helper method to define mock.On call
//   - post models.Post
func (_e *MockPostRepo_Expecter) UpdatePost(post interface{}) *MockPostRepo_UpdatePost_Call {
	return &MockPostRepo_UpdatePost_Call{Call: _e.mock.On("UpdatePost", post)}
}

func (_c *MockPostRepo_UpdatePost_Call) Run(run func(post models.Post)) *MockPostRepo_UpdatePost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.Post))
	})
	return _c
}

func (_c *MockPostRepo_UpdatePost_Call) Return(_a0 models.Post, _a1 error) *MockPostRepo_UpdatePost_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPostRepo_UpdatePost_Call) RunAndReturn(run func(models.Post) (models.Post, error)) *MockPostRepo_UpdatePost_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPostRepo creates a new instance of MockPostRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostRepo {
	mock := &MockPostRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
