// Code generated by mockery v2.30.1. DO NOT EDIT.

package repository

import (
	models "Nix_trainee_practic/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: id
func (_m *MockUserRepo) Delete(id int64) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id int64
func (_e *MockUserRepo_Expecter) Delete(id interface{}) *MockUserRepo_Delete_Call {
	return &MockUserRepo_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockUserRepo_Delete_Call) Run(run func(id int64)) *MockUserRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockUserRepo_Delete_Call) Return(_a0 error) *MockUserRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepo_Delete_Call) RunAndReturn(run func(int64) error) *MockUserRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindByEmail provides a mock function with given fields: email
func (_m *MockUserRepo) FindByEmail(email string) (models.User, error) {
	ret := _m.Called(email)

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.User, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) models.User); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepo_FindByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByEmail'
type MockUserRepo_FindByEmail_Call struct {
	*mock.Call
}

// FindByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockUserRepo_Expecter) FindByEmail(email interface{}) *MockUserRepo_FindByEmail_Call {
	return &MockUserRepo_FindByEmail_Call{Call: _e.mock.On("FindByEmail", email)}
}

func (_c *MockUserRepo_FindByEmail_Call) Run(run func(email string)) *MockUserRepo_FindByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserRepo_FindByEmail_Call) Return(_a0 models.User, _a1 error) *MockUserRepo_FindByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepo_FindByEmail_Call) RunAndReturn(run func(string) (models.User, error)) *MockUserRepo_FindByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: id
func (_m *MockUserRepo) FindByID(id int64) (models.User, error) {
	ret := _m.Called(id)

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (models.User, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) models.User); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - id int64
func (_e *MockUserRepo_Expecter) FindByID(id interface{}) *MockUserRepo_FindByID_Call {
	return &MockUserRepo_FindByID_Call{Call: _e.mock.On("FindByID", id)}
}

func (_c *MockUserRepo_FindByID_Call) Run(run func(id int64)) *MockUserRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockUserRepo_FindByID_Call) Return(_a0 models.User, _a1 error) *MockUserRepo_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepo_FindByID_Call) RunAndReturn(run func(int64) (models.User, error)) *MockUserRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: user
func (_m *MockUserRepo) Save(user models.User) (models.User, error) {
	ret := _m.Called(user)

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(models.User) (models.User, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(models.User) models.User); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(models.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepo_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserRepo_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - user models.User
func (_e *MockUserRepo_Expecter) Save(user interface{}) *MockUserRepo_Save_Call {
	return &MockUserRepo_Save_Call{Call: _e.mock.On("Save", user)}
}

func (_c *MockUserRepo_Save_Call) Run(run func(user models.User)) *MockUserRepo_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.User))
	})
	return _c
}

func (_c *MockUserRepo_Save_Call) Return(_a0 models.User, _a1 error) *MockUserRepo_Save_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepo_Save_Call) RunAndReturn(run func(models.User) (models.User, error)) *MockUserRepo_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
