// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	jwt "github.com/golang-jwt/jwt"
	mock "github.com/stretchr/testify/mock"

	models "Nix_trainee_practic/internal/models"

	requests "Nix_trainee_practic/internal/http/requests"
)

// CommentService is an autogenerated mock type for the CommentService type
type CommentService struct {
	mock.Mock
}

// DeleteComment provides a mock function with given fields: id
func (_m *CommentService) DeleteComment(id int64) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetComment provides a mock function with given fields: id
func (_m *CommentService) GetComment(id int64) (models.Comment, error) {
	ret := _m.Called(id)

	var r0 models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (models.Comment, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) models.Comment); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Comment)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCommentsByPostID provides a mock function with given fields: postID, offset
func (_m *CommentService) GetCommentsByPostID(postID int64, offset int) ([]models.Comment, error) {
	ret := _m.Called(postID, offset)

	var r0 []models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int) ([]models.Comment, error)); ok {
		return rf(postID, offset)
	}
	if rf, ok := ret.Get(0).(func(int64, int) []models.Comment); ok {
		r0 = rf(postID, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = rf(postID, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveComment provides a mock function with given fields: commentRequest, postID, token
func (_m *CommentService) SaveComment(commentRequest requests.CommentRequest, postID int64, token *jwt.Token) (models.Comment, error) {
	ret := _m.Called(commentRequest, postID, token)

	var r0 models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.CommentRequest, int64, *jwt.Token) (models.Comment, error)); ok {
		return rf(commentRequest, postID, token)
	}
	if rf, ok := ret.Get(0).(func(requests.CommentRequest, int64, *jwt.Token) models.Comment); ok {
		r0 = rf(commentRequest, postID, token)
	} else {
		r0 = ret.Get(0).(models.Comment)
	}

	if rf, ok := ret.Get(1).(func(requests.CommentRequest, int64, *jwt.Token) error); ok {
		r1 = rf(commentRequest, postID, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateComment provides a mock function with given fields: commentRequest, id
func (_m *CommentService) UpdateComment(commentRequest requests.CommentRequest, id int64) (models.Comment, error) {
	ret := _m.Called(commentRequest, id)

	var r0 models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(requests.CommentRequest, int64) (models.Comment, error)); ok {
		return rf(commentRequest, id)
	}
	if rf, ok := ret.Get(0).(func(requests.CommentRequest, int64) models.Comment); ok {
		r0 = rf(commentRequest, id)
	} else {
		r0 = ret.Get(0).(models.Comment)
	}

	if rf, ok := ret.Get(1).(func(requests.CommentRequest, int64) error); ok {
		r1 = rf(commentRequest, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCommentService creates a new instance of CommentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentService {
	mock := &CommentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
