// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	models "Nix_trainee_practic/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// CommentRepo is an autogenerated mock type for the CommentRepo type
type CommentRepo struct {
	mock.Mock
}

// DeleteComment provides a mock function with given fields: id
func (_m *CommentRepo) DeleteComment(id int64) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int64) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetComment provides a mock function with given fields: id
func (_m *CommentRepo) GetComment(id int64) (models.Comment, error) {
	ret := _m.Called(id)

	var r0 models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (models.Comment, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(int64) models.Comment); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(models.Comment)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCommentsByPostID provides a mock function with given fields: postID, offset
func (_m *CommentRepo) GetCommentsByPostID(postID int64, offset int) ([]models.Comment, error) {
	ret := _m.Called(postID, offset)

	var r0 []models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(int64, int) ([]models.Comment, error)); ok {
		return rf(postID, offset)
	}
	if rf, ok := ret.Get(0).(func(int64, int) []models.Comment); ok {
		r0 = rf(postID, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = rf(postID, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveComment provides a mock function with given fields: comment
func (_m *CommentRepo) SaveComment(comment models.Comment) (models.Comment, error) {
	ret := _m.Called(comment)

	var r0 models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Comment) (models.Comment, error)); ok {
		return rf(comment)
	}
	if rf, ok := ret.Get(0).(func(models.Comment) models.Comment); ok {
		r0 = rf(comment)
	} else {
		r0 = ret.Get(0).(models.Comment)
	}

	if rf, ok := ret.Get(1).(func(models.Comment) error); ok {
		r1 = rf(comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateComment provides a mock function with given fields: comment
func (_m *CommentRepo) UpdateComment(comment models.Comment) (models.Comment, error) {
	ret := _m.Called(comment)

	var r0 models.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(models.Comment) (models.Comment, error)); ok {
		return rf(comment)
	}
	if rf, ok := ret.Get(0).(func(models.Comment) models.Comment); ok {
		r0 = rf(comment)
	} else {
		r0 = ret.Get(0).(models.Comment)
	}

	if rf, ok := ret.Get(1).(func(models.Comment) error); ok {
		r1 = rf(comment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCommentRepo creates a new instance of CommentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentRepo {
	mock := &CommentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
