FROM golang:latest

WORKDIR /app/src

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .

COPY migrations ../migrations

RUN go build -o ../Nix_trainee_practic cmd/main.go

WORKDIR /app

RUN rm -rf src

EXPOSE 8080

CMD [ "/app/Nix_trainee_practic" ]